// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package auth

import (
	"context"
)

const userLogin = `-- name: UserLogin :one
SELECT 
    u.user_role
FROM 
    "user" AS u
JOIN auth AS a ON 
    a.user_id = u.id
WHERE a.user_name = $1 AND a.password = $2
`

type UserLoginParams struct {
	UserName string
	Password string
}

func (q *Queries) UserLogin(ctx context.Context, arg UserLoginParams) (URole, error) {
	row := q.db.QueryRow(ctx, userLogin, arg.UserName, arg.Password)
	var user_role URole
	err := row.Scan(&user_role)
	return user_role, err
}
