basePath: /api/v1
host: localhost:3400
info:
  contact: {}
  description: This is a doctors appointment project to do booking, consultation,
    etc
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Doc-Appointment
  version: 1.0.0
paths:
  /doctor:
    get:
      operationId: Doctor Operations
      responses: {}
      summary: Main router for doctor
  /patient:
    get:
      operationId: Patient Operations
      responses: {}
      summary: Main router for patient
swagger: "2.0"
