// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package postgres

import (
	"context"
)

const userLogin = `-- name: UserLogin :one
SELECT 
    u.user_role,
    u.id
FROM 
    "user" AS u
JOIN auth AS a ON 
    a.user_id = u.id
WHERE a.user_name = $1 AND a.password = $2
`

type UserLoginParams struct {
	UserName string
	Password string
}

type UserLoginRow struct {
	UserRole URole
	ID       int32
}

func (q *Queries) UserLogin(ctx context.Context, arg UserLoginParams) (UserLoginRow, error) {
	row := q.db.QueryRow(ctx, userLogin, arg.UserName, arg.Password)
	var i UserLoginRow
	err := row.Scan(&i.UserRole, &i.ID)
	return i, err
}
